Cleaned up README.md formatting and fixed path for data-on-chain exam…
coti-io/coti-sdk-python-examples pull request #5
Opened 2024-06-18 22:50 UTC by rakshasa

…ple.

2024-06-24 21:27 UTC, danielgruesso commented on README.md
> +1.  Navigate to the `contracts` directory in the `confidentiality-contracts` directory inside the `coti-sdk-python-examples` project.
```suggestion
1.  Navigate to the `data_onchain` directory in the `confidentiality-contracts/examples` directory inside the `coti-sdk-python-examples` project.
```

2024-06-24 21:29 UTC, danielgruesso commented on README.md
> +    cd confidentiality-contracts/contracts
```suggestion
    cd coti-sdk-python-examples/examples/data_onchain
```

2024-06-24 21:30 UTC, danielgruesso requested changes
Thanks for the contribution! Please review suggestions.

2024-06-24 21:50 UTC, rakshasa commented
Those changes in the PR were made because it was required to execute the examples.

As such the suggestions are incorrect as far as the steps I did to successfully run the test.

2024-06-25 18:32 UTC, danielgruesso commented
Thanks @rakshasa. Please pull the latest version, I believe some of the issues have already been addressed. Thanks again.

2024-07-08 10:49 UTC, closed without merging